
# serializer for the key
key.serializer=org.apache.kafka.common.serialization.StringSerializer

# serializer for the value
value.serializer=org.apache.kafka.common.serialization.StringSerializer

# kafka broker(s) to connect to
bootstrap.servers=localhost:9092

# acknowledgment level for producer requests
acks=all

# maximum number of retries for failed sends
retries=3

# size of the batch for sending messages (in bytes)
batch.size=16384

# linger time (in milliseconds) before sending a batch
linger.ms=1

# Buffer memory size for the producer (in bytes)
buffer.memory=33554432

# compression type for messages (e.g. none, gzip, snappy, etc.)
compression.type=none

# maximum size of a request (in bytes)
max.request.size=1048576

# timeout for requests (in milliseconds)
request.timeout.ms=30000

# enable idempotence for exactly-once delivery
# ensures that messages are delivered exactly once to a kafka topic, even in the case of retries due to transient failures
# when enabled, the producer can safely retry sending a message without the risk of duplicating it in the topic
enable.idempotence=true

# partitioner class (for custom partitioning logic)
partitioner.class=org.apache.kafka.clients.producer.internals.DefaultPartitioner
