
# app name
spark.app.name=Sparkler

# master url (e.g. local or cluster mode)
spark.master=local[*]

# number of shuffle partitions (default is 200, adjust based on data size)
spark.sql.shuffle.partitions=200

# enable/disable dynamic allocation of executors
spark.dynamicAllocation.enabled=true

# minimum and maximum number of executors for dynamic allocation
spark.dynamicAllocation.minExecutors=1
spark.dynamicAllocation.maxExecutors=10

# TEST adjust driver host:port for yarn
# explicitly configured to avoid dynamic binding issues with localhost
spark.driver.host=127.0.0.1
spark.driver.port=7077

# driver memory allocation
spark.driver.memory=1g

# executor memory allocation
spark.executor.memory=2g

# executor cores
spark.executor.cores=2

# TEST adjust executor host for yarn
# explicitly configured to avoid dynamic binding issues with localhost
spark.executor.host=127.0.0.1

# enable/disable event logging
spark.eventLog.enabled=true
spark.eventLog.dir=file:/Users/juliengaupin/Documents/code/clusters/apache-spark/eventlogs
